---
title: "Assignment3"
author: "smandumu"
date: "11/14/2019"
output: html_document
---

Cereals <- read.csv("Cereals.csv")
Cereals
# Remove all cereals with missing values
C <- na.omit(Cereals)
C
C <- subset( C, select = -c(1,2,3))
C <- as.data.frame(C)
#View(C)
C <- scale(C)
str(C)
# Question a
library(factoextra)    #clustering visualization
library(cluster)       #clustering algorithms
library(NbClust)       #determine optimal no. of clusters
head(C)
str(C)
#View (C)
HC <- hclust(dist(C,method = "euclidean"),method = "complete")
HC
plot(HC,hang = -1, cex=0.6)

# methods to assess best
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")
# function to compute coefficient
ac <- function(x) {  agnes(C, method = x)$ac}
library(purrr)
map_dbl(m, ac)
# The approach used by Ward describes the best clustering mechanism of the four approaches tested
HCW <- agnes(C, method = "ward")
pltree(HCW, cex = 0.6, hang = -1, main = "Dendrogram of agnes")  #  visualize the dendrogram
#*****End of Question a****#

# Question b

# slicing the dendogram on the longest path, 4 is the optimal level of clusters.
# Cut tree into 4 groups
sub_grp <- cutree(HCW, k = 4)
# Number of members in each cluster
table(sub_grp)
rect.hclust(HCW, k = 4)
#******End Of Question b****#

#Question c
# CLuster Stability
library(caret)
c1<-na.omit(Cereals)
c1<-as.data.frame(c1)
NewC <- createDataPartition(c1$calories,p=0.5,list = FALSE)
  
trainC<-c1[NewC,] # Partition A
testC<-c1[-NewC,] # Partition B

ac <- function(x) {  agnes(trainC, method = x)$ac}
map_dbl(m, ac)
# The approach used by Ward describes the best clustering mechanism of the four approaches tested
ac <- function(x) {  agnes(testC, method = x)$ac}
map_dbl(m, ac)
# The approach used by Ward describes the best clustering mechanism of the four approaches tested


pltree(agnes(scale(trainC[,-c(1:3)]),method = "ward"), cex = 0.6, hang = -1, main = "Dendrogram of agnes")
rect.hclust(agnes(scale(trainC[,-c(1:3)]),method = "ward"), k = 3)

pltree(agnes(scale(testC[,-c(1:3)]),method = "ward"), cex = 0.6, hang = -1, main = "Dendrogram of agnes")
rect.hclust(agnes(scale(testC[,-c(1:3)]),method = "ward"), k = 3)
library(dendextend)
train1 <- agnes(scale(trainC[,-c(1:3)]),method = "ward")
test1 <- agnes(scale(testC[,-c(1:3)]),method = "ward")


dend1 <- as.dendrogram(train1) 
dend2<-as.dendrogram(test1) 

tanglegram(dend1,dend2)

cor_cophenetic(as.dendrogram(train1),as.dendrogram(test1))

cor_bakers_gamma(as.dendrogram(train1),as.dendrogram(test1))

# Question d
na.omit(Cereals)
d <-cbind(,clust)
res1[res1$clust==1,]